STAGE_METADATA = {

    "Reality": {
        "purpose": "The observed world prior to interpretation.",
        "inputs": [],
        "outputs": ["Signals"],
        "questions": [
            "What exists?",
            "What is occurring?",
        ],
    },

    "Signals": {
        "purpose": "Observable information generated by reality.",
        "inputs": ["Reality"],
        "outputs": ["Localization"],
        "questions": [
            "Which signals exist?",
            "Which are trustworthy?",
        ],
    },

    "Localization": {
        "purpose": "Associate signals with location, source, or object.",
        "inputs": ["Signals"],
        "outputs": ["Witness Formation"],
        "questions": [
            "Where did the signal originate?",
            "Can it be localized?",
        ],
    },

    "Witness Formation": {
        "purpose": "Establish independently observable evidence.",
        "inputs": ["Localization"],
        "outputs": ["Interpretation"],
        "questions": [
            "Can another observer verify this?",
            "Has witnessing occurred?",
        ],
    },

    "Interpretation": {
        "purpose": "Assign meaning to witnessed observations.",
        "inputs": ["Witness Formation"],
        "outputs": ["Accountability"],
        "questions": [
            "What does the evidence indicate?",
            "What remains unknown?",
        ],
    },

    "Accountability": {
        "purpose": "Determine responsibility and traceability.",
        "inputs": ["Interpretation"],
        "outputs": ["Correction Capacity"],
        "questions": [
            "Who can act?",
            "Who is responsible?",
        ],
    },

    "Correction Capacity": {
        "purpose": "Assess whether meaningful correction remains possible.",
        "inputs": ["Accountability"],
        "outputs": ["Recovery"],
        "questions": [
            "Can the trajectory still change?",
            "Is intervention still meaningful?",
        ],
    },

    "Recovery": {
        "purpose": "Determine whether recoverability remains available.",
        "inputs": ["Correction Capacity"],
        "outputs": ["Governability"],
        "questions": [
            "What survives?",
            "What can still recover?",
        ],
    },

    "Governability": {
        "purpose": "Evaluate whether ongoing correction remains sustainable.",
        "inputs": ["Recovery"],
        "outputs": ["Future Influence"],
        "questions": [
            "Can the system remain governable?",
            "Can correction continue?",
        ],
    },

    "Future Influence": {
        "purpose": "Measure remaining ability to influence future outcomes.",
        "inputs": ["Governability"],
        "outputs": ["Inspectable Unknowns"],
        "questions": [
            "What influence remains?",
            "What opportunities still exist?",
        ],
    },

    "Inspectable Unknowns": {
        "purpose": "Explicitly preserve unresolved observations.",
        "inputs": ["Future Influence"],
        "outputs": [],
        "questions": [
            "What remains unknown?",
            "What should be investigated next?",
        ],
    },
}


def get_stage_metadata(stage):

    return STAGE_METADATA.get(stage, {})