from enum import Enum


class ExecutionAuditEventType(str, Enum):
    INTENT_RECEIVED = "INTENT_RECEIVED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_SUCCEEDED = "EXECUTION_SUCCEEDED"
    EXECUTION_FAILED = "EXECUTION_FAILED"