from enum import Enum


class ExecutionDifferenceType(str, Enum):

    MATCH = "MATCH"

    VALUE_DIFFERENCE = "VALUE_DIFFERENCE"

    MISSING_RUNTIME = "MISSING_RUNTIME"

    MISSING_RECONSTRUCTION = "MISSING_RECONSTRUCTION"

    ORDER_DIFFERENCE = "ORDER_DIFFERENCE"

    UNKNOWN = "UNKNOWN"